[package]
name = "day9"
version = "0.1.0"
authors = ["Jack Blanchard <jack.blanchard88@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc_input = {path = "../aoc_input"}